### ISSUE TITLE
configuration.yaml support

### ISSUE THREAD

**Issue by aftertommy** [scottyphillips/echonetlite_homeassistant#113]
I can't seem to tell which way the Home Assistant project is leaning, but it would be really great if echonetlite_homeassistant supported defining configurations via the configuration.yaml file. I have a (surprisingly) large number of echonet devices. Once in a while I find myself having to remove my devices and re-add them via the web ui. This gets the job done for sure, but some devices take quite a bit of time, such as Daikin AC units. It would be fantastic if I could instead just define my devices/entities up front with their IP address, name, location, and configuration options.

**Comment by nao-pon** [comment]
The echonetlite integration requires retrieving and configuring the corresponding properties for each device. Therefore, it is necessary to proceed with the configuration while interacting with the device using the configuration flow.
It's not impossible to set these required parameters in configuration.yaml, but it would require knowledge of this protocol.

I think the first priority is to reduce the chances of reconfigulation. For example, if a change in IP address is the reason you need to reconfigure, it is best to fix the device's IP address.

For example, specify a static IP in the device settings, or fix the IP address assigned by a DHCP server such as a router as a MAC address.

**Comment by aftertommy** [comment]
Oh for sure - I already do assign static IPs to each device. It’s when something goes awry that it can be a tough process to re-setup.

**Comment by nao-pon** [comment]
It's good thing they are already static IP addresses.  So if this integration's bug is the reason why you need to reconfigure, I'd like to solve it. 

If something goes wrong, please create another issue to explain what the situation is.

Also please let us know if you notice anything in the debug log or something.

**Comment by aftertommy** [comment]
Will do! I had opened an issue about how my integrations were all suddenly failing to load after upgrading to latest echonetlite and restart, but I closed it after resolving by updating HA from 2022.6 to 2022.8. I’ll post a link in a moment.

**Comment by aftertommy** [comment]
https://github.com/scottyphillips/echonetlite_homeassistant/issues/112

**Comment by scottyphillips** [comment]
configuration.yaml is deprecated and we won’t be bringing it back sorry. All official integrations are supposed to be migrating to config flow.

**Comment by aftertommy** [comment]
thank you!
