### ISSUE TITLE
Version 3.7.0 will be released soon

### ISSUE THREAD

**Issue by nao-pon** [scottyphillips/echonetlite_homeassistant#118]
Hi, All! I've planning to release version 3.7.0 soon. Please try the master branch if possible and let us know if it works or if there are any problems.

- Fixed a bug with home air conditioner humidity settings. ( #116 )
- Changed the unique ID generation method so that unique IDs to avoid duplication even on devices with multiple instances.
   - But unique ID of existing configurations will not be changed. However, if you delete and reconfigure the integration, the unique ID will change, so some adjustments, such as automation, may be required.
- Added a step to automatically obtain an IP address if possible in the integration's configuration flow.
- Immediate states updates via service "homeassistant.update_entity".
- Polling to update other attributes when data updates are received for air conditioners, lights, and fans.
- Support Low voltage smart electric energy meter (Smart Mater / B-Root Service).
- Other minor fixes and refactorings.

**Comment by nao-pon** [comment]
It released.

**Comment by lordCONAN** [comment]
Release Notes for 3.7.0 has some errors.

`Support Low voltage smart electric energy meter (Smart Mater / B-Root Service).`

Should read

Support Low voltage smart electric energy meter (Smart **Meter** / B-**Route** Service).


@nao-pon Thanks for all your hard work!

**Comment by nao-pon** [comment]
@lordCONAN I fixed that's typo. Thanks! 👍 By the way, do you have a smart meter with B-Route Service enabled? If you have it, please check if it works.

**Comment by lordCONAN** [comment]
I do have a smart meter, but haven't had 中国電力 turn on B-Route yet, as I have no hardware to connect with B-Route. I was thinking about getting a [B-Route module](https://www.amazon.co.jp/HEMS%E7%94%A8-Wi-SUN%E3%83%A2%E3%82%B8%E3%83%A5%E3%83%BC%E3%83%AB-Wi-SUN-Route-B-%E5%B0%82%E7%94%A8/dp/B08XZ6XHJJ).

**Comment by nao-pon** [comment]
OK! If you buy it, please try it!

I'm also considering buying a similar one, but it's expensive because it's not really necessary for me...

**Comment by nao-pon** [comment]
It caught my attention, so I looked into it, and it seems that I need something to interconnect Wi-SUN and Ethernet, such as a [Wi-SUN gateway kit (RpiWi-001)](https://www.switch-science.com/products/6160). ESP-32 etc. may be possible if we program it. I'm looking for any good libraries.

**Comment by ammgws** [comment]
Do you already have a smart meter? It seems like you need to apply to your power company to get the authentication details for using Wi-SUN too, e.g. https://www.kansai-td.co.jp/application/smart-meter/low-pressure/index.html

**Comment by nao-pon** [comment]
Yes, It has a smart meter installed. But I don't have a Wi-SUN module. What I'm thinking is he will create a Wi-SUN <-> WiFi LAN bridge such as with BP35C0-T01 and ESP-32. can i? can't i? I'm still gathering more information.

It might be easier to simply get the information from the USB dongle and expose it via MQTT instead of this integration. . .

After all, the Wi-SUN gateway kit (RpiWi-001) mentioned earlier might be the easiest.

**Comment by nao-pon** [comment]
To connect with the B route service of Japanese smart meters, I chose the Wi-SUN gateway kit. However, since the service account has not been activated yet, we will let you know the outcome once the service account is activated.

However, since this topic is only for Japan, I will not continue it here and will continue it in Japanese on my repository.

- https://github.com/nao-pon/echonetlite_homeassistant/issues/2
