### ISSUE TITLE
Mitsubishi PEA-M100GAA won't connect

### ISSUE THREAD

**Issue by Gitspecial** [scottyphillips/echonetlite_homeassistant#125]
The integration says Failed to setup

Error log

2023-02-05 16:15:28 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Mitsubishi for echonetlite
File "/config/custom_components/echonetlite/__init__.py", line 202, in async_setup_entry

**Comment by nao-pon** [comment]
@Gitspecial It may be because the version of Home Assistant Core is old.

Try changing line 202 of "/config/custom_components/echonetlite/init.py" to the following and restart HA.

```python
    # this api is too recent (around April 2021): hass.config_entries.async_setup_platforms(entry, PLATFORMS)
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
```
to
```python
    if hasattr(hass.config_entries, 'async_forward_entry_setups'):
        await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
    else:
        # this api is too recent (around April 2021) but keep for backwards compatibility
        hass.config_entries.async_setup_platforms(entry, PLATFORMS)
```

**Comment by Gitspecial** [comment]
Thanks, yes it's working after I update the HA.
