### ISSUE TITLE
Integration will fail in HA version 2023.3

### ISSUE THREAD

**Issue by kerryland** [scottyphillips/echonetlite_homeassistant#127]
I noticed this in the HA logs:

Detected integration that called async_setup_platforms instead of awaiting async_forward_entry_setups; this will fail in version 2023.3. Please report issue to the custom integration author for echonetlite using this method at custom_components/echonetlite/__init__.py, line 134: hass.config_entries.async_setup_platforms(entry, PLATFORMS)

I am not yet using 2023.3, and can't say for sure if this problem has landed yet, but it sounds close!

**Comment by kerryland** [comment]
The fix might be trivial: https://github.com/hacs/integration/commit/96a1a9e6ed57f8cc24c3579ac9ddc8447e23977c

**Comment by scottyphillips** [comment]
I checked the code and i don't think this should be an issue because the only place 'async_forward_entry_setups' is mentioned is commented out in line 201 of __init__.py
` # this api is too recent (around April 2021): hass.config_entries.async_setup_platforms(entry, PLATFORMS)`

**Comment by kerryland** [comment]
Ha. That's awesome. Sorry for the interruption
