### ISSUE TITLE
Echonetlite devices become unavailable a while after HA restart

### ISSUE THREAD

**Issue by yzzaJ** [scottyphillips/echonetlite_homeassistant#132]
Hi. I'm struggling to troubleshoot this much, and I apologise for some of the vagueness around the problem description.
I have three echonetlite devices shown as thermostats. After HA has been running for a while (about a day or so), the thermostats go "blank", and the HA logs say that the device has became unavailable. A restart of HA will bring the devices back available and controllable for a while again. All three echonetlite devices become unavailable at the same time, while another thermostat I have that doesn't use echonetlite remains available.

This behaviour started a while back, probalby a couple of months. I can't recall if it is a certain date or software version of HA or echonetlite that this started with. I have subsequently updated HA to the latest version 2023.4.6, and switched the installation of echonetlite from manually installed to instead be instaled via HACS with the latest version. The issue still occurs.

If this isn't a known issue (I couldn't see any related issues) can you please suggest what troubleshooting I could do. Thank you.

**Comment by axlback** [comment]
My integration has also stopped working. I believe it is because async_setup_platforms has been deprecated, which would require the maintainer to fix. Since scottyphillips has passed this on, I’m not sure if it’s going to happen.

If it doesn’t thanks very much @scottyphillips for writing this in the first place, it’s been brilliant for me while it lasted.

**Comment by yzzaJ** [comment]
Thanks for commenting @axlback, that has given me something to work with. I've rolled Home Assistant back to version 2034.2.5, which is the version before async_setup_platforms is deprecated. Will see if that stablises things.

**Comment by nao-pon** [comment]
@yzzaJ , @axlback Sorry to keep you waiting. We just released version 3.7.3 which contains a fix for this issue.

**Comment by yzzaJ** [comment]
Oh, that's awesome thank you! No worries about the wait, just glad this project is still being maintained. I have upgraded and looking good.
