### ISSUE TITLE
Unable to find this integration listed in Home Assistant integration search?

### ISSUE THREAD

**Issue by victorhooi** [scottyphillips/echonetlite_homeassistant#135]
Hi,

I previously installed this integration, by manually downloading the files to `custom_components`. 

I've now deleted that directory, and reloaded HA.

This is HA 2023.5.3

However, if I go to Integrations, and try to search for Echonet, it doesn't seem to come up:

<img width="1098" alt="image" src="https://github.com/scottyphillips/echonetlite_homeassistant/assets/243499/631267c7-3c4f-41b1-852a-5a242073a48b">

Is there some trick to making this integration appear in the integration search results in HA?

**Comment by scottyphillips** [comment]
It’s because you deleted the directory, you to reinstall the directory and then do a search. Ideally you should use HACS to install it.

**Comment by benflux** [comment]
Is it a custom repository? I can't find this by searching in HACS

**Comment by ctaylor-bne** [comment]
yeah its in HACS just hit download which overrode my manual download.
![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/92408688/b2f92b61-c074-49ae-8ac0-c944cfbf46c4)

**Comment by benflux** [comment]
what am i missing?

![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/31230445/172c4f8c-2892-4bb2-b861-9778bafc734a)

**Comment by ctaylor-bne** [comment]
make sure to click this
![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/92408688/d6cf13ee-bd27-4566-94f6-e40fddbc10a3)
then search it there 
![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/92408688/67738784-a717-43ac-942f-881b0fb1fb2a)

**Comment by ctaylor-bne** [comment]
![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/92408688/c168bb0f-4e4d-4b7e-9ac0-c8f9039575b9)

**Comment by bigtag9128** [comment]
Hi, 

Just freshly installed HA 2023.06.2 and trying to get this integration added but I get an error. It seems like I have the same error that started this thread, but it looks like the HA interface is a little different now and I cant get this repo added.

If I go to Settings > Add-ons, then click the 3-dot button on the top right, then click Repositories and try to add this repo, I get an error saying it is not a valid add-on repository (see pic)

![echonetlite repo add error](https://github.com/scottyphillips/echonetlite_homeassistant/assets/137164320/2cf842ef-4af2-4b78-8ae4-ae487a123a96)

Is there some rookie mistake I have made?


Thanks

**Comment by bigtag9128** [comment]
Not to worry worked it out eventually. Needed to properly install HACS (I used this guide https://www.makeuseof.com/home-assistant-install-hacs-custom-addons/) then via HACS could get ECHONETLite Platform installed.
