### ISSUE TITLE
Can you enable ECHONET lite only with official Mitsubishi AU/NZ Wifi App?

### ISSUE THREAD

**Issue by romanorac** [scottyphillips/echonetlite_homeassistant#138]
Can you enable ECHONET lite only with the official Mitsubishi AU/NZ Wifi App?

I have a MAC-577IF2-e adapter in my MSZ-AP42VGK AC, but I don't see the enable ECHONET lite option in the MELCloud iOS application. I'm in the EU.

Am I using the wrong app or does MAC-577IF2-e not support it? Where can I download the official Mitsubishi AU/NZ Wifi App if the former is the case?

**Comment by scottyphillips** [comment]
![IMG_4838](https://github.com/scottyphillips/echonetlite_homeassistant/assets/26150540/735cc6a5-9da2-4e7f-b59f-7898163bb623)
This is the AU/NZ app. I have no idea if you can download or access via EU App Store.

**Comment by scottyphillips** [comment]
For what’s it’s worth, I am not able to download the MELCLOUD app here in the Antipodes…

**Comment by qupada** [comment]
According to the NZ website, only the "568" model WiFi adapter has the feature

https://www.mitsubishi-electric.co.nz/wifi/learn_echonet.aspx

I expect too that the region you buy the unit in dictates which regional cloud service it connects to, so you wouldn't be able to onboard the adapter in the NZ cloud service even if you could get the app.

**Comment by romanorac** [comment]
In the README.md it says it also supports MAC-578IF2-E
