### ISSUE TITLE
Echonetlite failed to load after Homeassistant update yesterday

### ISSUE THREAD

**Issue by petermnz1** [scottyphillips/echonetlite_homeassistant#139]
Hi, First thanks for all the work you  do providing this addon , its been working great for my mitsubishi aircon for months. But yesterday I updated homeasisstant as new versions come out, I always do and has never been a problem until now. 
Heres the log:
Setup failed for custom integration echonetlite: Unable to import component: cannot import name 'EPC_SUPER' from 'pychonet.lib.epc' (/usr/local/lib/python3.11/site-packages/pychonet/lib/epc.py)
June 26, 2023 at 3:22:23 PM – (ERROR) setup.py
Cheers Peter

**Comment by scottyphillips** [comment]
Sounds like your install has somehow got corrupted as I updated last night with no issues. Not seeing anyone else raising this as an issue either. Uninstall and Reinstall the custom component and see if that helps.

**Comment by petermnz1** [comment]
Ok Thanks for your reply, I rolled back my install and its working again. I'll retry the update and do as you suggested if it fails again. Cheers
