### ISSUE TITLE
AC Measured outdoor air temperature - no longer provided, but still working sometimes?

### ISSUE THREAD

**Issue by girkers** [scottyphillips/echonetlite_homeassistant#147]
I have both MSZ-AGP25VGD and MSZ-AP80VGD units in my home and on all integrations it shows the entity, sensor AC Measured outdoor air temperature, as being restored. And when you look at sensor it states "This entity is no longer being provided by the echonetlite integration".

My issue is that on one of my AP80 units this sensor is working, still has the aforementioned text, and am I very pleased with this, but for my other AP80 and the AP25 units they don't work.

Is there anyway to get this sensor to work with the other AP80 and the smaller AP25 units?

**Comment by rscoleNZ** [comment]
I have two MSZ-AGP20VGD and a MSZ-AGP25VGD all connected to a single outdoor unit. They appear to be reporting the outdoor temperature fine, ie the reported temp in HA matches the Mitsi Wi-Fi app.

I recently had errors reporting on the outdoor sensor for the MSZ-AGP25VGD only, which meant the MSZ-AGP25VGD was unusable within HA. I cannot recall, but there may have been a IP change. After removing it from HA, and re-installing did not work, I had to switch echonet off/on, while installing/re-installing in HA to get it working again. This was all in the last week, I cannot recall what the error message was, but it was not as you provided.

**Comment by girkers** [comment]
I have tried this with a couple of my units, remove then device, then turn echonet off, wait, and then turned it back on. I give it a little bit and then add the device back. On one unit it worked, on the other two (2) I have tried, it has gotten rid of the status "restored", but when you look at the entity for the Outdoor temperature I get the error, "The entity is unavailable"

![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/66195700/08536358-3f99-4668-88ab-574e41b44417)

I will try with my other that don't work and see how I get on, but any other tips?

**Comment by girkers** [comment]
I found the steps on how to get it to work.

1. Delete Device from HA
2. Turn off Echonet in, i use, Wi-Fi Control
3. Wait (I don't know how long I just went and did other things)
4. Turn on Echonet
5. Wait, again undetermined how long
6. Turn on air conditioner
7. Wait
8. Turn off air conditioner
9. Wait
10. Add Device in HA and I found that Autodiscovery picked it up straight away.
11. Follow the steps to add it and your good to go.

**Comment by girkers** [comment]
I would like to reopen this issue as the sensor continues to drop off. I did an update of the component this morning and for most of my Air Conditioners it dropped off the outside temperature.

I have followed my steps from before and this has added it back, but the bug is why did it disappear when it had been working?

Here is screenshot showing when it stopped working and after adding it back:
![image](https://github.com/scottyphillips/echonetlite_homeassistant/assets/66195700/f77c9156-fe06-4c7b-b8cc-a1cd168da8e6)

**Comment by tom3q** [comment]
Was the AC running all the time? Two of mine don't provide the temperature properties when they are off.

**Comment by girkers** [comment]
I think you may have cracked it there!

I want to confirm though is that an issue with units or the protocol?

Is there anything I can do to test it?

**Comment by tom3q** [comment]
I think enabling the debug logs for the echonet lite device in HA would give you the view on what the AC unit is reporting back. Mine basically sends back the value that corresponds to "unavailable" (which is some kind of a big number, like 0xFFFE hex or something among those lines).

**Comment by scottyphillips** [comment]
There is work being done by @nao-pon to try to support DHCP configured devices where the IP address changes but I would configure fixed addressing, configure each device individually and not use the auto discovery as I never ever see this issue on my own system. I have a fixed IP address and it is solid as a rock. I would also enable the force polling option as well as this may be symptomatic.

if you are running the master version and not a release, please be aware that there is a breaking change at present that renames all the entities.

**Comment by tom3q** [comment]
Ah, yeah, I also have mine at static IP addresses, so that could be also a factor. Good point.

**Comment by khcnz** [comment]
The smaller units only provide outside air temp when running / for a short period around the running time, I think that's in the mitsubishi documentation somewhere.

**Comment by khcnz** [comment]
Do you still have the Mitsubishi app? You can see there my multi head unit seems to always run the exterior temp in the app, however the standalone AP25 I have doesn't and only shows room temp after sometime when it's off. 

So I suggest we close the ticket unless there is a better suggestion of what this entity should report when there is no outside temp

**Comment by girkers** [comment]
The bigger units appear to be the same, I have two (2) 9kw systems and they display the same issue.

I think that it must be a power thing, the inside head units are always powered, they need to receive commands, but the outdoor unit is simple a dumb unit that turns on and off, thus they don't have power, thus the sensor doesn't work.

A solution I thought of but no sure how well it would be received is have the option of being able to "poll" for the outside temperature. What I mean by that is can we work out how long it takes to get the outdoor temperature and set up a automation/whatever to "poll" the outdoor unit by turning on the A/C and then once you have your outside temp turn it off.

Just a thought.

**Comment by scottyphillips** [comment]
@girkers you could do that with a Home Assistant automation and probably a template sensor of some description. But thats outside the remit of this custom component.
