### ISSUE TITLE
"Mono Functional Lighting" (0x0291) is considered a "Switch" rather than a "Light"

### ISSUE THREAD

**Issue by rubyroobs** [scottyphillips/echonetlite_homeassistant#153]
Currently trying to set this integration up for my [Panasonic "Advance Series Link Plus" WTY24173 LED dimmer switches](https://www2.panasonic.biz/jp/densetsu/haisen/switch_concent/advance/lineup/linkplus/3_4wire_touch/) via the official [WTY2001 wireless adapter](https://www2.panasonic.biz/scvb/a2A/opnItemDetail?item_no=WTY2001&catalog_view_flg=1&contents_view_flg=1&vcata_flg=1) which uses ECHONET Lite.

The integration works great out the box for non-dimmable switches but does not allow for adjustment of brightness on the dimmable ones. I did some digging and I believe this is due to only `0x0290` being considered a light in [light.py](https://github.com/scottyphillips/echonetlite_homeassistant/blob/3013fceeeb874508c9e6d3fdd1bea0f5e155397c/custom_components/echonetlite/light.py#L32) and [switch.py](https://github.com/scottyphillips/echonetlite_homeassistant/blob/3013fceeeb874508c9e6d3fdd1bea0f5e155397c/custom_components/echonetlite/switch.py#L53).

I was locally able to get this working by modifying the `custom_components` and adding another `or` there to consider `eojgc` equal to `0x02` and `eojcc` equal to `0x91` as a light. From my testing this seems to literally fix the issue - lights dim properly and I've confirmed updates are being sent as expected and read properly from the switches themselves and their official software.

I will create a PR for this too, but wanted to record this temporary fix and issue first :)

**Comment by scottyphillips** [comment]
@rubyroobs your contribution is most welcome!! Thank you! 

It is beyond ridiculous that here in Australia I cannot buy a decent quality smart dimmer switch (let alone install it myself) due to our draconian electrical safety standards, and yet people all over the world are using code that I wrote for a ducted air conditioner to control smart light switches sold by a massive Japanese tech giant… 🤦🏼‍♂️ I am going to have to gamble on some zigbee switches later this year…

**Comment by rubyroobs** [comment]
> @rubyroobs your contribution is most welcome!! Thank you!
> 
> It is beyond ridiculous that here in Australia I cannot buy a decent quality smart dimmer switch (let alone install it myself) due to our draconian electrical safety standards, and yet people all over the world are using code that I wrote for a ducted air conditioner to control smart light switches sold by a massive Japanese tech giant… 🤦🏼‍♂️ I am going to have to gamble on some zigbee switches later this year…

If it makes you feel any better I'm only using these Panasonic switches because it's the only option available at the switch level in Japan since we have specific radio restrictions and 100V power (everywhere else starts 120V usually...)

Thanks for merging so quick - if you could bump the version that would be appreciated so I can redownload in my HA :) I hope you get round to buying the Zigbee smart switches, going "full" smart home is super fun :)
