### ISSUE TITLE
Unable to find device

### ISSUE THREAD

**Issue by luizdanieldesouza** [scottyphillips/echonetlite_homeassistant#155]
Hi,

First of all I appreciate such development. I have a module (MAC-568IF-E) which was working well before. Unfortunately I had to reinstall HA and now cannot find the device. Everything works fine through the Mitsubishi app.

just wondering if any of you might be able to help me identify the root cause.

much appreciated 

Dan

**Comment by scottyphillips** [comment]
Check your IP address and if necessary assign a static IP addresses in DHCP using the MAC address of each adapter.

**Comment by luizdanieldesouza** [comment]
Thank Scott - the issue was on the HA Docker installation. Unfortunately HA was not installed/running on network = host. 

Many thanks again.

Dan
