### ISSUE TITLE
Investigate why component is dropping off.

### ISSUE THREAD

**Issue by scottyphillips** [scottyphillips/echonetlite_homeassistant#167]
Ive noticed with the edge releases a pattern where my climate device will eventually fail and drop off and be marked as unavailable. Reloading the custom component is enough to fix it. This issue stated occurring with the 3.80 betas that are currently in pre-release, so I need to investigate further before this is released. For everyone else please do not run 3.80 unless you are okay to assist with troubleshooting.

**Comment by nao-pon** [comment]
I added a feature in 3.8.0 that stops polling when a device is marked unavailable. That could be the cause, so I'll put it back.

**Comment by tom3q** [comment]
I also observed the same with one of my air conditioners (Hitachi). Let me see with the current HEAD. Thanks for the quick fix.

On a side note, I guess WiFi, especially 2.4 GHz, is kind of inherently prone to various random communication issues, so some resilience on the HA side is probably a good idea.

**Comment by lordCONAN** [comment]
Also noticed the same. My aircon and solar power systems are both now unavailable.

**Comment by tom3q** [comment]
With the HEAD version, I don't see the Hitachi AC getting stuck in
unavailable state anymore. Thanks again!

2024年2月13日(火) 9:20 lordCONAN ***@***.***>:

**Comment by get-trucked** [comment]
I was wondering why the heat pump kept dropping off, I made some unrelated changes that had me head scratching

Thanks for fixing it so quickly

**Comment by nao-pon** [comment]
I'm sorry for your concern. This issue appears to have been resolved in 3.8.0-beta7 and later. We will keep it open until the 3.8.0 release, so please let us know if you run into any issues.

**Comment by scottyphillips** [comment]
Closing as resolved
