### ISSUE TITLE
Entity None (<class 'custom_components.echonetlite.climate.EchonetClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method.

### ISSUE THREAD

**Issue by mattbodley** [scottyphillips/echonetlite_homeassistant#172]
ogger: homeassistant.components.climate
Source: components/climate/__init__.py:354
Integration: Climate ([documentation](https://www.home-assistant.io/integrations/climate), [issues](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+climate%22))
First occurred: 6:14:23 PM (12 occurrences)
Last logged: 6:14:23 PM

Entity None (<class 'custom_components.echonetlite.climate.EchonetClimate'>) does not set ClimateEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/scottyphillips/echonetlite_homeassistant/issues
Entity None (<class 'custom_components.echonetlite.climate.EchonetClimate'>) does not set ClimateEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/scottyphillips/echonetlite_homeassistant/issues
Entity None (<class 'custom_components.echonetlite.climate.EchonetClimate'>) implements HVACMode(s): heat, cool, dry, fan_only, heat_cool, off and therefore implicitly supports the turn_on/turn_off methods without setting the proper ClimateEntityFeature. Please create a bug report at https://github.com/scottyphillips/echonetlite_homeassistant/issues

**Comment by scottyphillips** [comment]
This has been resolved in the beta 3.8.0 so closing
