### ISSUE TITLE
Latest upgrade broke Panasonic Advance lighting

### ISSUE THREAD

**Issue by mayberryjp** [scottyphillips/echonetlite_homeassistant#178]
Hi,
I haven't had time to debug and capture logs yet but the latest Echonet lite HA integration update seems to have broken the Panasonic Advance light interaction over Echonet

It was working without issue for a year, i upgraded, it stopped working. The system is still accessible and works from its normal controller local website

I will get some logs soon

**Comment by khcnz** [comment]
Might be the same issue, or maybe not.. but I've just updated and HA has created all new entities for the sensors which has broken all existing dashboards / automations - might pay to check if it's stopped working as the entity ids have changed

**Comment by mayberryjp** [comment]
Yes, you're right. It's all new entities. I see them now. Thanks

**Comment by mayberryjp** [comment]
new entities

**Comment by karlchaffey** [comment]
Well I don't know if we should close the ticket, it shouldn't have created new entities! 
@nao-pon without detailed inspection, it might have been this PR  https://github.com/scottyphillips/echonetlite_homeassistant/pull/164 was it expected to recreate all entities?

**Comment by mayberryjp** [comment]
FYI it only renamed entities for one device. the other 5 were unchanged
