### ISSUE TITLE
Energy-related sensors are not enabled by default

### ISSUE THREAD

**Issue by leonunix** [scottyphillips/echonetlite_homeassistant#179]
Do you have the same problem?
Now i don't it is ha problem or echonetlite problem.
My HA version is 2024.4.3
echonetlite is lastest version.
After update , i find some sensor became unavailabe. Like air conditioner power sensor. Both two air conditioner power sensor became unavailable. And others the same. Like Storage battery. Half of sensors is unavailable.

![スクリーンショット 2024-04-18 15 54 34](https://github.com/scottyphillips/echonetlite_homeassistant/assets/12597965/9dcd9af5-026e-4c59-a05f-5fcd44879762)

**Comment by nao-pon** [comment]
@leonunix In HACS, from this integration screen, enable the debug function, restart HA, wait about 5 minutes, then disable the debug function to download the log. Can you attach that log file here?

**Comment by leonunix** [comment]
hi nao-pon
here is my log. 

[home-assistant_echonetlite_2024-04-19T12-22-53.042Z.log](https://github.com/scottyphillips/echonetlite_homeassistant/files/15040285/home-assistant_echonetlite_2024-04-19T12-22-53.042Z.log)

**Comment by nao-pon** [comment]
Looking at the logs, it appears that some data cannot be retrieved at first, but after several inquiries, it appears to be available.

Were the sensors currently marked "unavailable" previously available?

**Comment by leonunix** [comment]
thank you for confirm it. But after data come. It should be became available. But it still unavailable.

**Comment by nao-pon** [comment]
A closer look at the logs shows that some sensor entities may have switched to input entities. For example, AC discharge amount setting value might be configured as a numeric input entity. The sensor entity that has been switched to the input entity is no longer usable, so there is no problem in deleting it.

If you used the value of that sensor in the past, such as in an automation, change it to reference the value of the input entity, or create a sensor in a helper that references the value of the input entity.

**Comment by leonunix** [comment]
hi nao-pon
The best problem is measured_cumulative_power_consumption never show again of my air con. Did you measured_cumulative_power_consumption display normal?

**Comment by nao-pon** [comment]
Is the "Enable energy-related sensors (if available)" (ja:"エネルギー関連のセンサーを有効にする(取得可能な場合)") setting in the device settings enabled?

**Comment by leonunix** [comment]
hi nao-pon
this options default enable. But after i disable/enable it. It works. Thank you very much. It maybe old configuration problem.

**Comment by leonunix** [comment]
Maybe not. I delele device ,and add it again. The Enable energy-related sensors is default on. But sensor will not display on entity. When i disable/enable it. It work fine.

**Comment by nao-pon** [comment]
Yes, I have confirmed that the option does not take effect on a new setup. This is a bug so I will fix it.

**Comment by nao-pon** [comment]
@leonunix It fixed in version 3.8.1! Thanks! 👍
