### ISSUE TITLE
Deprecated Constants

### ISSUE THREAD

**Issue by dean0909** [scottyphillips/echonetlite_homeassistant#184]
Hello, thanks for your custom integrations, it works flawlessly with my Mitsubishi AC's and is lightning fast! I note that in my HASS logs, there is a warning about the constants utilised being deprecated by release 2025.1. I have pasted a sample log entry below for reference. Is this something which can be rectified prior? Otherwise any guidance will be highly appreciated.

<><><><><><><><><><>
**2024-06-03 22:03:16.741 WARNING (ImportExecutor_0) [homeassistant.const] DEVICE_CLASS_HUMIDITY was used from echonetlite, this is a deprecated constant which will be removed in HA Core 2025.1. Use SensorDeviceClass.HUMIDITY instead, please report it to the author of the 'echonetlite' custom integration**
<><><><><><><><><><>

**Comment by nao-pon** [comment]
Thanks for your report. This is already fixed on b848810117d72cb2e6534829467d7bff132d408d. Please update this component.

**Comment by dean0909** [comment]
Thanks for your quick reply and apologies, I was unaware of the update. Your support is appreciated!
