### ISSUE TITLE
Support for .5 degree increments

### ISSUE THREAD

**Issue by thomasbergernz** [scottyphillips/echonetlite_homeassistant#187]
I like to utilise the ability to set the temperature by .5 increments.

**Comment by khcnz** [comment]
As far as I remember, this isn't possible in the econetlite spec

https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_F/SpecAppendixF_e.pdf

The value is 0x0 - 0x32 for EPC 0xB3 which gives the supported range of 0-50 degrees in one byte increments.

**Comment by thomasbergernz** [comment]
<img width="1228" alt="image" src="https://github.com/user-attachments/assets/ec613a7e-87bc-4b79-9ab2-5dacdad23107">
The measurement seems to be in 0.1 increments supported

**Comment by nao-pon** [comment]
Unfortunately, that's the specs for the thermometer, not the air conditioner.
You can find the air conditioner specs below.

- https://echonet.jp/wp/wp-content/uploads/pdf/General/Standard/Release/Release_R/Appendix_Release_R_rev2_E.pdf
  - P128
![echonet jp](https://github.com/user-attachments/assets/e3db89b3-8360-44c5-987c-3ee23f84d917)
