### ISSUE TITLE
Entity None (<class 'custom_components.echonetlite.fan.EchonetFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. 

### ISSUE THREAD

**Issue by yhi264** [scottyphillips/echonetlite_homeassistant#188]
ロガー: homeassistant.components.fan
ソース: components/fan/__init__.py:295
統合: ファン (ドキュメンテーション, 問題)
最初に発生: 2024年8月26日 06:25:11 (2 発生)
最終ログ: 2024年8月26日 06:25:11

Entity None (<class 'custom_components.echonetlite.fan.EchonetFan'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/scottyphillips/echonetlite_homeassistant/issues
Entity None (<class 'custom_components.echonetlite.fan.EchonetFan'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/scottyphillips/echonetlite_homeassistant/issues

**Comment by nao-pon** [comment]
This is a feature that was applied from Home Assistant Core 2024.8. I will fix this. Thanks! 👍 

see. https://developers.home-assistant.io/blog/2024/07/19/fan-fanentityfeatures-turn-on_off/
