### ISSUE TITLE
KDK wifi ceiling fan (not able to reverse fan spin direction)

### ISSUE THREAD

**Issue by lysiong** [scottyphillips/echonetlite_homeassistant#190]
Hi, I have KDK wifi ceiling fan, the HA side can show exactly the current status of the fan(ON OFF status, reverse, fan speed) but I can only ON & OFF the fan through the HA, other features like reverse, fan speed are not able to set from the HA interface. Once I toggle the switch for fan direction, it will revert back to original position after few second. The fan did beep when I set the reverse on HA but somehow the fan didn't reverse. 

<img width="416" alt="image" src="https://github.com/user-attachments/assets/f12e281a-e8ac-4da1-b19e-11cef3db19a7">

**Comment by nao-pon** [comment]
I checked #142 again and it seems that some of the data implemented in the pychonet library is incorrect, so I will make a correction. I'm going to close this and move on to #142.
