### ISSUE TITLE
Circular reference breaks loading in home assistant

### ISSUE THREAD

**Issue by josh-shaw-dev** [scottyphillips/echonetlite_homeassistant#192]
Hey.

I think this commit broke the loading into home assistant

Cant load the custom component due to a circular reference which I think is from the below commit, I tested the commit before it and it loads however this commit does not

https://github.com/scottyphillips/echonetlite_homeassistant/commit/9223f8fc916deb66bcd65e1653004040ce509447#diff-fcfdfd9773401069af4737299de4b85f09172755d33da1710560f4a6c2c39cb1R51

Pretty sure this is the offending import as its importing from the fan which also requires the const file
`from custom_components.echonetlite.fan import (`

**Comment by nao-pon** [comment]
@josh-shaw-dev Thanks! 👍
