### ISSUE TITLE
Support Bathroom dryer (0x02-0x73)

### ISSUE THREAD

**Issue by seya99** [scottyphillips/echonetlite_homeassistant#197]
I am a regular user of your services, and I am currently trying to operate the bathroom ventilation, drying, and heating unit [UFD-112PWA]. However, at present, I am only able to retrieve the Operation status.
Would it be necessary to wait for an update to Pychonet in order to proceed with other operations?
 I'm a complete novice at this and any help would be greatly appreciated. Thanks so much!

EOJ: 027301

**Comment by nao-pon** [comment]
@seya99 Let me take a look at it!

**Comment by nao-pon** [comment]
I applied it to [my edge branch](https://github.com/nao-pon/echonetlite_homeassistant) in response to the Bathroom dryer. Can you try my edge branch?

You can easily try out my edge branch by adding the following URL to your custom repository in HACS:

- https://github.com/nao-pon/echonetlite_homeassistant

**Comment by seya99** [comment]
Great! I successfully obtained the status without any issues!
Unfortunately, I wasn't able to send the ventilation command to the device, but it seems that this is due to the device's specifications, so there's nothing we can do about it.
Thank you! Thanks to you, I was able to visualize the operational status that I wanted!

**Comment by nao-pon** [comment]
I released Version 3.8.6 to this issue fixed. 👍 @seya99 Thansks! 👍
