### ISSUE TITLE
Subcontroller temperatures in ducted units?

### ISSUE THREAD

**Issue by Dekks** [scottyphillips/echonetlite_homeassistant#39]
Thanks again for your ongoing contributions!

I have a master and sub controller in a ducted configuration.
Temperature is available in both of the controllers which are in different rooms. 
Is access to that available via Echonet and, if so, can it be added to the interface?
D

**Comment by scottyphillips** [comment]
umm, probably not... at least not as part of the standard.. The ECHONET Lite spec supports 'indoor temperature', 'temperature setting','outdoor temperature' (if available). Don't really have the option of extracting additional temperature settings, you would need to get your hands dirty with the python library and see what your attributes are.

**Comment by Dekks** [comment]
Thanks. I suspect there's additional complexity because the "indoor" temperature in the ducted units can be an average of sensors, depending on configuration. Probably too messy to deal with but I'll try and summon some ancient skills to have a prowl around.

**Comment by scottyphillips** [comment]
Yes, i remembered when I discovered that the panel itself had a temperature sensor and that the Aircon guys hadn’t bothered to configure it, before then it was using the indoor unit sensor and giving false readings. It was a game changing discovery lol.

Scott

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by Dekks** [comment]
Don't get me started on Aircon guys that have no clue what they're doing. You didn't happen to find a source for comprehensive programming manuals for the Mitsubishi devices by any chance?
Last night, the ducted unit I have doesn't return an outside temperature at all, although it does show the target temperature and the temperature it is recorded (from the returned air going through the ceiling unit, I assume).

**Comment by scottyphillips** [comment]
https://www.mitsubishielectric.com.au/assets/IM_PEA-RPGAA_(KD79M111H02.pdf
Section 8 explains how to change the temperature sensor from indoor unit to remote control

**Comment by scottyphillips** [comment]
Closing this.
