### ISSUE TITLE
HACS integration is broken

### ISSUE THREAD

**Issue by scottyphillips** [scottyphillips/echonetlite_homeassistant#41]
Good morning,

I have renamed the repo this morning as it is no longer just Mitsubishi centric and can be used by all kinds of ECHONETLite devices. Unfortunately publishing to HACS has become more strict these days so I am just working through the various pull requests to get this sorted out

**Comment by ammgws** [comment]
I think this can be closed now?

**Comment by scottyphillips** [comment]
I’m still waiting for the PR to be approved.
