### ISSUE TITLE
HACS description

### ISSUE THREAD

**Issue by ammgws** [scottyphillips/echonetlite_homeassistant#43]
Not sure where it grabs this from but the description that shows up when searching this in HACS is old:

> ECHONETLite Platform
> A Home Assistant custom component for use with ECHONET enabled Mitsubishi HVAC systems. 

It should probably be something like

> ECHONETLite Platform
> A Home Assistant custom component for use with ECHONET enabled devices such as Mitsubishi HVAC systems and more.

**Comment by scottyphillips** [comment]
That was part of the old description i think, HACS integration is a bit of a mess (i'm having to chase up PRs with the home-assistant brands and wheel repos). We can keep track of HACS issues there.

**Comment by ammgws** [comment]
Ah I think it might be grabbing it from the GitHub repo "about" part.
