### ISSUE TITLE
Occasional 0 values?

### ISSUE THREAD

**Issue by njs50** [scottyphillips/echonetlite_homeassistant#50]
Not sure if it's relevant, but if I look at my graphs I see occasional instances where all the values drop to 0:

![image](https://user-images.githubusercontent.com/55112/135166677-70b98471-7daa-4ac9-8be9-438637bc574e.png)

No errors in the logs and "Measured value of room temperature" seems to retain the correct value. Seems extra odd that target temp is also going to 0.

This is on your previous test branch (2.2), updating to the latest now, didn't see any issues about this so thought i'd post this in case it's not something fixed already.

Aside from that I can report everything has been running well on a ducted unit PEAD-M125JAA(D). Would be nice to control the lossnay + bypass one day, I suspect that isn't possible, unless some other regions app can do it.

**Comment by njs50** [comment]
fwiw this isn't a problem for me other than making my graphs less pretty :p but i imagine if you were depending on those temps you might end up triggering some automations you didn't really want triggered.

**Comment by khcnz** [comment]
Are you still seeing this on the newest version? Might pay to increase logging level to see what is going on with returned values if you are.

**Comment by njs50** [comment]
haven't seen it since updating, so I'll close this. cheers :-)
