### ISSUE TITLE
PV Buy goes heavily negative from time to time

### ISSUE THREAD

**Issue by dmshimself** [scottyphillips/echonetlite_homeassistant#51]
I've noticed a few times that the Buy attribute goes very negative on my system for a short period.  It doesn't happen very often, maybe once a week.  For example today it went to over -5,000 KWh at around, but not exactly, 7am for a couple of minutes.  Normally this value goes from 0 upwards.

This throws off the HA energy calculation, so my self consumes use today is 68,190 %  Nice!

However, I'm guessing Buy should never really go negative :-), so any suggestions on the best way of filtering this out in some way appreciated.

**Comment by dmshimself** [comment]
As a test, I've popped in a slght mod to the value_emplate to be ...

{{ [states.sensor.Inverter_9010KETL205W0005.attributes.seller,0] | max}}

In the very limited testing I've done in the HA development tools, it seems to be working so far.  Time will tell!

**Comment by khcnz** [comment]
Is that from a template sensor, from an echonet device?

**Comment by dmshimself** [comment]
Yes, I modified the suggested template sensor that is shown in the echonetlite docs and the device is a Mitsubishi ducted system.  I'm happy to provide extra docs or debug info as needed.

**Comment by khcnz** [comment]
Ah yea ok, I think this can happen if the device can't be queried at that time (the sensor should go unavailable I think). If you look at the history of your main entity I think you'll see that it has gone to 'unavailable' at that time. you see 0 

Your approach should work, but you can also do something like in this thread to detect an unavailable result and return 'unavailable' in the template as well https://community.home-assistant.io/t/template-sensor-dealing-with-unavailable-values/109674 if your template returns 'unavailable' then i think that data won't be included in the energy stats.

**Comment by dmshimself** [comment]
Many thanks - I'll monitor and see what happens.....

**Comment by scottyphillips** [comment]
Hey mate can you provide your example workaround code?

**Comment by dmshimself** [comment]
Sure thing  Replace the template sensors from the docs for buy and seller with the following changing the name of your invertor to be your one. 

      pv_seller:
        value_template: '{{ [states.sensor.Inverter_9010KETL205W0005.attributes.seller,0] | max }}'
        friendly_name: 'PV Seller'
        
      pv_buy:
        value_template: '{{ [states.sensor.Inverter_9010KETL205W0005.attributes.buy,0] | max }}'
        friendly_name: 'PV Buy'

**Comment by scottyphillips** [comment]
Hey mate just out of curiosity, what make/model of PV system are you using that is ECHONET enabled? I might incorporate any information about it including these template settings and then close this ticket if that is allright?

**Comment by dmshimself** [comment]
Sure thing.  Mine is a

GW10KL-ET by GoodWe
Firmware: 04029-03-S10 (02041-11-S00)

All running very well
