### ISSUE TITLE
Works with ducted Mitsubishi PEA-M100GAA

### ISSUE THREAD

**Issue by aheath70** [scottyphillips/echonetlite_homeassistant#54]
Not really an issue, but wanted to let you know that it works with my new 10Kw ducted system beautifully. 

I too am in Australia, and can't access MELCloud, so went on the hunt for something that would work with the wifi controller directly, and I found this.

Thanks for you work - it works really well, and in my opinion is better than the MELCloud integration anyway - this uses local control and is not cloud polling, so all the better.

**Comment by scottyphillips** [comment]
Thanks everyone for this update I’ll try to merge when I have free time.
