### ISSUE TITLE
Some of sensor value is hex in daikin air conditioner

### ISSUE THREAD

**Issue by leonunix** [scottyphillips/echonetlite_homeassistant#60]
In my case

sensor.daikin_living_air_measured_instantaneous_power_consumption 
sensor.daikin_living_air_measured_value_of_room_relative_humidity

up two sensor read value is hex. humidity will get value of '2d'. It can not process of HA. So how can i change it to dec value.

**Comment by scottyphillips** [comment]
Can you update to the latest and please let me know if resolved. The humidity and instant power consumption values were being returned as raw bytecodes, I have now hopefully resolved this in the back end to be correctly parsed as integer values.

**Comment by leonunix** [comment]
it work. thank you very much
