### ISSUE TITLE
Home Assistant reads current power draw as 65,534 when AC is turned off

### ISSUE THREAD

**Issue by rigelpesit** [scottyphillips/echonetlite_homeassistant#62]
I have a Fujitsu Nocria AC and it integrates well with home assistant thanks to this project.
Only problem I have is that when I have it turned off it displays '65,534' as its current power draw. I think its just a data type issue as if it was a signed 16bit int it would have been '-2'.

![hass_ac_power](https://user-images.githubusercontent.com/11290912/152668596-63cb523a-92bf-41f1-848f-c243d07d85d4.png)

**Comment by scottyphillips** [comment]
Yeah I think reading the spec that is an underflow code (0xFFFE), just need to work out a sensible method of marking it as unavailable when this condition is met

**Comment by scottyphillips** [comment]
This issue has been addressed in the recent update, can you please update and confirm the issue is resolved?

**Comment by rigelpesit** [comment]
Thank you so much. I updated a few days ago and now it shows at 1W when turned off.
