### ISSUE TITLE
Maximum temperature too high... I'm heating my house...not my greenhouse! :-p

### ISSUE THREAD

**Issue by ChirpyTurnip** [scottyphillips/echonetlite_homeassistant#66]
Hi,

Love the ability to set max/min temps! :-)

Is it possible to increase the scale range? Max for example is 25-35C...but I don't want anyone to set the heaters higher than 22C as 25C is already too hot in our house...let alone 35C...I can't even imagine that!

Could also swap sliders for explicit values? 

Keep up the good work, your integration rocks!

CP.

**Comment by scottyphillips** [comment]
I would rather sliders because otherwise I’ll get flooded with complaints about invalid values. But I can certainly fine tune those values no problem

**Comment by ChirpyTurnip** [comment]
Nice! :-)

No rush.... I'm not sure what a sensible value set would be...maybe:

Min - 15 to 25
Max - 18 to 30

It's hard to imagine many people would want to go cooler than 15 (I don't
think heat pumps can go lower anyway), and heating above 30 is also
unlikely as I don't think most will go that high either.

Anyway, that range there's an overlap of  7 degrees... So reasonably
flexible.

Hope that helps!

CP.

**Comment by ChirpyTurnip** [comment]
Wow! Super fast turn around....looks awesome, new values dialled in. No
more bloody kids setting the temperature too high or too low. :-)

Thanks heaps!
