### ISSUE TITLE
Target temp goes to -3deg when it's off

### ISSUE THREAD

**Issue by khara02** [scottyphillips/echonetlite_homeassistant#69]
Thank you for developing echonetlite_homeassistant,
I am using it for my Panasonic CS-288CX2 and it's working fine.

But there are an isue that the target temp changes to -3 degrees while the air conditioner is off.
How does it be fiexed? This issue seems quite similar to #58.

![capture](https://user-images.githubusercontent.com/55570523/158004047-37582730-879a-4ae5-b043-da10ab3e47a2.jpg)

Thank you.

**Comment by scottyphillips** [comment]
Good evening, Target Temperature should have been fixed in some of the recent updates, what version are you running and have you updated recently via the HACS store?

Code for target temp fix (0xFD) below.

```
    @property
    def target_temperature(self):
        """Return the temperature we try to reach."""
        if ENL_HVAC_SET_TEMP in self._connector._update_data:
            temp = self._connector._update_data[ENL_HVAC_SET_TEMP]
            if temp != -3:
                return temp
        return None
```

**Comment by scottyphillips** [comment]
It was fixed on 7th of Feb by the one and only @tom3q

**Comment by khara02** [comment]
> It was fixed on 7th of Feb by the one and only @tom3q so please update to the latest version. (well, _should_ be fixed)

Thank you for your reply,
I just have updated to 3.4.7 via the HACS.
Now it changes target temp into null instead of -3 deg.

**Comment by scottyphillips** [comment]
That’s the correct behaviour, I don’t think there is a cleaner way of presenting it as that is the state as reported by the HVAC (unavailable). I’ll have to talk to the brains trust about what we can do moving forward..

**Comment by tom3q** [comment]
Hmm, for me the target temperature disappears completely. I don't see "null".
![image](https://user-images.githubusercontent.com/400091/158011033-77b2c914-3753-4e36-b6a9-9a63ce3b4c76.png)
