### ISSUE TITLE
Setting fan speed to "quiet".

### ISSUE THREAD

**Issue by mishnz** [scottyphillips/echonetlite_homeassistant#70]
There is a mode on my remote that sets the unit to "quiet" mode, which seems to be separate to low/high fan settings.
https://github.com/futomi/node-echonet-lite/blob/master/EDT-01.md

The above URL shows the following:
**Normal/highspeed/silent operation setting**
**EPC: 0xB2** - Code "**3**" is "**Silent Operation**"

Do you have any thoughts on how we could expose "silent"/"quiet" mode to Home Assistant, other integrations like Sensibo already have this functionality.

**Comment by scottyphillips** [comment]
It's a little piece of missing functionality in the HomeAirConditioner class. Probably in this instance we would have to use a select entity -> split systems already have this option for directional airflow settings. It wouldn't be part of the standard climate entity however as that is actually quite limited in its customisation.

**Comment by scottyphillips** [comment]
I haven't forgotten about this, and I have coded in the necessary functionality into the back end. I am thinking we can probably shim this into the climate entity as a 'preset' option; otherwise it will be available as a select.

**Comment by scottyphillips** [comment]
Hi there, can you please download the 3.5.2-beta. Quiet mode should now be working as a preset functionality within the Climate entity. 
You may need to go to hacs -> click three dots on echonetlite -> select 'redownload' -> select 'allow beta versions' -> select 3.5.2-beta.
https://hacs.xyz/docs/faq/select_version

**Comment by mishnz** [comment]
Hi,

Removed the existing install and pulled down the code from github, confirmed that it's 3.5.2
It's not showing up for me in the Climate GUI (tried removing and readding the device).

**Comment by scottyphillips** [comment]
Can you enable debug mode against the custom component and send me the log file?

**Comment by scottyphillips** [comment]
Actually, if you are comfortable pulling direct from Git, can you pull the latest. I just realized I missed a couple of spots where I needed to add the silent operation flags.

**Comment by mishnz** [comment]
I'm not seeing any commits to master since your changes about an hour ago?

**Comment by scottyphillips** [comment]
Well thats because I forgot to push it 😞

**Comment by mishnz** [comment]
Deployed - still not showing up, assuming I'm looking in the right place? - debug logs attached inline
[echonetlite-debug-16-34.txt](https://github.com/scottyphillips/echonetlite_homeassistant/files/8790492/echonetlite-debug-16-34.txt)
.

**Comment by scottyphillips** [comment]
0xB2 (178)  is not in your 'set map' list, so I dont think its going to work regardless

**Comment by mishnz** [comment]
That is fascinating, I incorrectly assumed it would export "Silent"/"Quiet" mode over EchoNetLite in a consistent fashion.
I wonder what the chances are that one of the other items in the 'set map' list equates to "Silent"/"Quiet" mode.

**Comment by scottyphillips** [comment]
You would think so, but the vendors can be a bit daffy like that. 
These are all your get values:
128 - Operation Mode
160 - Fan Speed
176 - HVAC mode
129 - Install location
161 - auto direction 
130 - standard version information
131 - id number 
163 - swing mode 
179 - set temp 
164 - air vane vert 
133 - Measured cumulative power consumption 
165 - Air flow direction (horizontal) setting
134 - Manufacturers fault code
136 - Fault status
137 - Fault description 
138 - Manufacturer code, 
154 - Cumulative operating time 
187 - room temp, 
157 - Status change announcement property map, 
158 - Set property map,
159 - Get property map
190 - Outside temp
143 - Power-saving operation setting

In your get values you have one strange unique one: 208 (0xD0) - 'buzzer' which can be set but not get. 
But overall, nothing outside of what is in the spec.

**Comment by scottyphillips** [comment]
Anyways I am sure someone else will find this work useful regardless, sorry I wasn't able to help you in this instance.

**Comment by mishnz** [comment]
Thanks for all your assistance.
A final comment, using the Mitsubishi Android application there is no option for Quiet/Silent modes.  The only way to set Silent mode seems to be through Infrared.
This adds evidence that Mitsubishi simply haven't coded 0xB2/178 on the Echonet Lite card.

**Comment by scottyphillips** [comment]
No problem, thank you for using this custom component! I’m glad you find it useful.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
