### ISSUE TITLE
Support for MAC-578IF2-E

### ISSUE THREAD

**Issue by yzzaJ** [scottyphillips/echonetlite_homeassistant#71]
I understand this was written specifically for the MAC-568IF-E module, and it works for really well for the 2 units I have already. I recently had a new heat pump installed, and it came with a MAC-578IF2-E module and I can't seem to add it to HA. I get an error when trying to add the device (I do struggle putting the details in as for some reason the fields when adding a new Echonet Lite integration have no headings etc so I am guessing what to put in, have tried IP address then description and vice versa), but I'm not sure what the error is as again it has no text. 
I'd be more than happy to help troubleshoot this if this is something you would like to look at. I'm not a programmer by any means but if guided I can dig out logs, try things etc if that helps.

**Comment by xbmcnut** [comment]
I have at least three of those units installed yesterday and possibly a fourth in a MPEAD 71 ducted unit. Two of them work fine, and two don't report the room temp, power consumption or outdoor air temp.

I just added the IP address of the WiFi unit and have it a name and all four came into HA, it's just that I can only control two of them as the room temp is missing from the other two.

Maybe you can add a screenshot for your GUI issue?

**Comment by yzzaJ** [comment]
In the process of testing this it worked. I have restarted HA a few times since my OP, maybe that sorted it.
Anyway, for interest here is how the GUI looks, basically no dialogue boxes to indicate what information is required in what field. Thanks.
![Echonet Initial Screen](https://user-images.githubusercontent.com/67046503/167537305-12907f26-6d7a-487a-af55-0ff110103c78.PNG)

**Comment by yzzaJ** [comment]
Please feel free to close this issue thanks.

**Comment by xbmcnut** [comment]
Here is mine running under ECHONETLite version is 3.4.9 & HA Core version is 2022.5.3
![image](https://user-images.githubusercontent.com/1492137/167537776-4102370a-885e-4e6e-a241-6f64db73a1e0.png)

**Comment by yzzaJ** [comment]
Ok, looks like my version of ECHONETLIte is older. I'll look to upgrade. Thanks.
