### ISSUE TITLE
not connecting

### ISSUE THREAD

**Issue by ethicallymad** [scottyphillips/echonetlite_homeassistant#73]
Hi

Looks like you have done a great job on making this integration.

I have the latest version installed, and can open the echonet lite integration. When I enter my IP address though it cannot connect. 

I have echnonet activated in the Mitsubshi App, and have restarted everything, but still nothing :(

Any ideas? My heat pump is a MSZ-AP50VG, and works fine via the official app. 

Cheers

**Comment by scottyphillips** [comment]
i am about to push a newer version, a lot of these newer heatpumps are being a little troublesome. Give me a few minutes or so.

**Comment by ethicallymad** [comment]
Wow - now that is service with a smile ;-) 

Much appreciated. Really looking forward to start better automating the heating :-)

**Comment by scottyphillips** [comment]
Can you please update to 3.5.0 and try to add your HVAC and let me know?
Also, I have noticed sometimes that clearing browser cache and restarting HA helps.

**Comment by ethicallymad** [comment]
Sure thing. Will give that a shot now. Cheers.

**Comment by ethicallymad** [comment]
Still getting a 'Failed to connect' message :(

**Comment by ethicallymad** [comment]
Can I confirm that the IP address to add is that of the router?

**Comment by scottyphillips** [comment]
No, it will be a different IP address to the router. Your router may have a list of IP addresses that it has allocated to devices via the Wi-Fi. You may need some trial and error. 
In the same section where you enabled Echonet lite, there will be information concerning the MAC address under the wifi signal strength. In your router, this MAC address should be mapped to the IP address that your router handed out. 
If your router has the option to do so, you should really make a statically DHCP assigned IP address so the IP address doesnt change over time. You may need to do some light reading. :-D

**Comment by ethicallymad** [comment]
Gotcha, connected easily this time. However, it is coming up with the following error:

Logger: homeassistant.config_entries
Source: custom_components/echonetlite/__init__.py:64
Integration: ECHONET Lite ([documentation](https://www.github.com/scottyphillips/echonetlite_homeassistant), [issues](https://github.com/scottyphillips/echonetlite_homeassistant/issues))
First occurred: 14:23:54 (1 occurrences)
Last logged: 14:23:54

Error setting up entry Heat Pump for echonetlite
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 335, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/echonetlite/__init__.py", line 148, in async_setup_entry
    await echonetlite.async_update()
  File "/config/custom_components/echonetlite/__init__.py", line 274, in async_update
    _LOGGER.debug(polling_update_debug_log(update_data, self._eojgc, self._eojcc))
  File "/config/custom_components/echonetlite/__init__.py", line 64, in polling_update_debug_log
    debug_log = debug_log + f' - {EPC_CODE[eojgc][eojcc][value]} ({value:#x}): {values[value]}\n'
KeyError: 133

**Comment by ethicallymad** [comment]
(oh and just FYI, the router is already set to static IP)

**Comment by scottyphillips** [comment]
dang, one sec.

**Comment by ethicallymad** [comment]
No worries. Just appreciate you developing, and more impressively, maintaining this code!

**Comment by scottyphillips** [comment]
Can you try 3.5.1? Should fix the logging issue. I got tripped up because unfortunately my system is actually a bit feature deficient so I have to code a little blindly sometimes.

**Comment by ethicallymad** [comment]
sure thing 👍

**Comment by ethicallymad** [comment]
Looks like it has found it and setup all the entities correctly, and first test looks like I have it operating from HA. 

NICE JOB!

Really, thanks so much :-)

**Comment by scottyphillips** [comment]
No problem!

**Comment by JGKarlin** [comment]
Many thanks for this integration. I lost all functionality on both a Daikin and Panasonic AC with version 3.5.1 and had to roll back to 3.4.9

**Comment by scottyphillips** [comment]
are you able to share logs of what the problem may be?

**Comment by JGKarlin** [comment]
I removed the and reinstalled, and it's working again on 3.5.1. Thank you again for this integration!

**Comment by scottyphillips** [comment]
No problems, I am curious as to why it failed during the upgrade; I always test on my own system but unfortunately there are so many systems out there now its impossible for me to test all scenarios. But I am glad it is working now. Please keep an eye on it and let me know if any dramas.
