### ISSUE TITLE
Invalid config - Setup failed for custom integration echonetlite:

### ISSUE THREAD

**Issue by shanport** [scottyphillips/echonetlite_homeassistant#74]
Hi, I have been able to connect to my two split systems and control them from HA, however for the past couple of weeks have been getting this error. 

Setup failed for custom integration echonetlite: Unable to import component: cannot import name 'UDPServer' from 'aioudp' (/usr/local/lib/python3.9/site-packages/aioudp/__init__.py)

I have tried to find a solution but being very new to HA have not had much luck. 

I am using 3.5.1 of ECHONETLite Platform Custom Component for Home Assistant and connected to Mitsubishi AC's
MSZ-AP25VG
MSZ-AP42VG

I would like to have this resolved, please let me know if there is more information you need.

Thanks Shannon

**Comment by scottyphillips** [comment]
Hi there, this looks like some sort of Python issue, How exactly are you running Home Assistant?

**Comment by scottyphillips** [comment]
I reckon that somewhere along the line the “aioudp” package has been messed up in your system. It really depends on how home assistant was installed in the first place.

**Comment by shanport** [comment]
Thanks for your reply, 

I received an update to HA and applied, then on restart this fixed the issue. 

Thanks, Shannon
