### ISSUE TITLE
Automatic configuration of main switch

### ISSUE THREAD

**Issue by nao-pon** [scottyphillips/echonetlite_homeassistant#84]
After checking the ECHONET specifications, it seems that 0x80 is defined by the super class and can be set on many devices.  If the Set property has 0x80, I think it's a good idea to automatically configure it as a switch entity.  If you haven't worked on adding this feature yet, should I send you a PR?

**Comment by nao-pon** [comment]
I was able to do it relatively quickly, so I created a PR(#85).

**Comment by scottyphillips** [comment]
Only concern I have is around that 0x80 it’s not mandatory for it to be a set value, at least from my understanding of the English version of the spec. Perhaps we can allow users to decide, by either creating both a sensor and switch or a checkbox.

https://echonet.jp/spec_object_rp1_en/

![B787673B-C4F1-42A5-B082-5287790C314D](https://user-images.githubusercontent.com/26150540/174936233-3eaa0a8a-bade-451b-a082-007ee5257c2e.png)
