### ISSUE TITLE
Inconsistent energy kWh readings from multi head Mitsubishi split systems

### ISSUE THREAD

**Issue by julianjwong** [scottyphillips/echonetlite_homeassistant#93]
I have two multi head condensers running 8 split systems total but I've noticed that the power consumption readings seem really wrong. Seems like one split system from each condenser may be consolidating usage across the other 3 heads per condenser. 

For example, I never use our lounge split system but it shows the highest reading each day. We do use our daughter's one for most of the day but that one shows low usage (both on the same condenser). Similarly I rarely use our study split system but it shows quite high. 

We have a range of these splits. Most are the smallest units but do have some larger ones.
https://www.mitsubishielectric.com.au/product/msz-ln25-35-50-60v-b-r-a1/

**Comment by scottyphillips** [comment]
I think you have answered your own question. Its the condenser that is ultimately doing all the work and I doubt the Mitsubishi is sophisticated enough to calculate how much power which indoor head unit is responsible for. I am making the educated guess here that the consolidated power figure is being derived from a 'primary' head unit, and I am making the assumption that your lounge unit, and your study unit, are the 'primary' splits. 

Just manage your energy readings on a per condenser basis, rather then a per split basis. I'm not going to be able to solve problems related to vendor implementations, all this library does is read the data that is presented to it by the systems in question.
