### ISSUE TITLE
Devices becoming unavailable

### ISSUE THREAD

**Issue by JGKarlin** [scottyphillips/echonetlite_homeassistant#99]
I have two air-conditioners configured with the integration. They work great once added, but over time, both devices become unavailable (though they do appear on their dedicated mobile apps). I suspect that it is because the IP address changes on the devices over time. Since there is no way to set a fixed IP address for the devices, I'm wondering if there is any solution to avoid having to constantly delete and recreate the integrations with their newly assigned IP addresses?

I've tried reserving their address in the router, but this doesn't seem to have any effect. I'm trying to configure the device tracker in HA now but there is not much documentation. Is anyone else having the same problem with the IP addresses changing on their devices?

**Comment by nao-pon** [comment]
I highly recommend fixing the IP address on your router.  Generally, IoT devices operate stably by fixing the IP address.  If your router has settings, it may not be set correctly.  Check that the MAC address of the device is correct.

**Comment by nao-pon** [comment]
However, I'm technically interested in dealing with IP address changes, so I'm currently implementing and experimenting with that feature. Hopefully I can send a PR.

**Comment by JGKarlin** [comment]
Thanks for your help! These two ECHONET devices are connected to my router (which has a fixed IP) through a Netgear extender. It's likely the extender is causing the problem. It appears to assign virtual MAC addresses to all devices connected through it. 

https://kb.netgear.com/24806/How-can-I-retrieve-the-virtual-MAC-address-from-the-Wi-Fi-Range-Extender-to-setup-an-Access-List 

I'm going to try connecting the AC units direct to the router (and not the extender) to see if that helps but I might have problems with the range of the WiFi signal.

**Comment by nao-pon** [comment]
The virtual MAC address seems to rewrite the vendor code of the device connected to the extender. Therefore, I think you should fix the IP with the rewritten MAC address.

The following is for reference ...

I used to use extenders to enhance WiFi radio waves, but as the number of IoT devices increases and more than 100 devices connect, the operation becomes very unstable, and I had to reboot sometimes router and extenders.

So I replaced it with TP-Link Mesh WIFi (Deco series) and it became very stable and I haven't restarted it for more than a year. I will tell you as one option.

**Comment by nao-pon** [comment]
I've played around with it to keep up with changes in IP addresses, but it seems difficult because this integration determines the device by IP address. I've also tried a fairly tricky method, but it can be complicated and unreliable.

**Comment by JGKarlin** [comment]
Many thanks for exploring a solution. I reset both my router and extender, and reconfigured the 2.4Ghz band to include WPA TKIP. I think these devices don't work well with AES only encryption on 802.11n, but that's only a theory. The devices are much more stable now with 802.11i TKIP.

**Comment by nao-pon** [comment]
It was good to be able to stabilize the device.  If there is no change in the IP address by stabilizing it, it will be a solution!

**Comment by nao-pon** [comment]
Keeping the echonetlite integration responsive to IP address changes proved difficult with the current configuration. That's an issue for the future, but at the moment there are no plans to do so. So I would like to close this.
